require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActivitingsController do

  # This should return the minimal set of attributes required to create a valid
  # Activiting. As you add validations to Activiting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActivitingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all activitings as @activitings" do
      activiting = Activiting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:activitings).should eq([activiting])
    end
  end

  describe "GET show" do
    it "assigns the requested activiting as @activiting" do
      activiting = Activiting.create! valid_attributes
      get :show, {:id => activiting.to_param}, valid_session
      assigns(:activiting).should eq(activiting)
    end
  end

  describe "GET new" do
    it "assigns a new activiting as @activiting" do
      get :new, {}, valid_session
      assigns(:activiting).should be_a_new(Activiting)
    end
  end

  describe "GET edit" do
    it "assigns the requested activiting as @activiting" do
      activiting = Activiting.create! valid_attributes
      get :edit, {:id => activiting.to_param}, valid_session
      assigns(:activiting).should eq(activiting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Activiting" do
        expect {
          post :create, {:activiting => valid_attributes}, valid_session
        }.to change(Activiting, :count).by(1)
      end

      it "assigns a newly created activiting as @activiting" do
        post :create, {:activiting => valid_attributes}, valid_session
        assigns(:activiting).should be_a(Activiting)
        assigns(:activiting).should be_persisted
      end

      it "redirects to the created activiting" do
        post :create, {:activiting => valid_attributes}, valid_session
        response.should redirect_to(Activiting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved activiting as @activiting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Activiting.any_instance.stub(:save).and_return(false)
        post :create, {:activiting => {}}, valid_session
        assigns(:activiting).should be_a_new(Activiting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Activiting.any_instance.stub(:save).and_return(false)
        post :create, {:activiting => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested activiting" do
        activiting = Activiting.create! valid_attributes
        # Assuming there are no other activitings in the database, this
        # specifies that the Activiting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Activiting.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => activiting.to_param, :activiting => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested activiting as @activiting" do
        activiting = Activiting.create! valid_attributes
        put :update, {:id => activiting.to_param, :activiting => valid_attributes}, valid_session
        assigns(:activiting).should eq(activiting)
      end

      it "redirects to the activiting" do
        activiting = Activiting.create! valid_attributes
        put :update, {:id => activiting.to_param, :activiting => valid_attributes}, valid_session
        response.should redirect_to(activiting)
      end
    end

    describe "with invalid params" do
      it "assigns the activiting as @activiting" do
        activiting = Activiting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Activiting.any_instance.stub(:save).and_return(false)
        put :update, {:id => activiting.to_param, :activiting => {}}, valid_session
        assigns(:activiting).should eq(activiting)
      end

      it "re-renders the 'edit' template" do
        activiting = Activiting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Activiting.any_instance.stub(:save).and_return(false)
        put :update, {:id => activiting.to_param, :activiting => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested activiting" do
      activiting = Activiting.create! valid_attributes
      expect {
        delete :destroy, {:id => activiting.to_param}, valid_session
      }.to change(Activiting, :count).by(-1)
    end

    it "redirects to the activitings list" do
      activiting = Activiting.create! valid_attributes
      delete :destroy, {:id => activiting.to_param}, valid_session
      response.should redirect_to(activitings_url)
    end
  end

end
