require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlternateItemingsController do

  # This should return the minimal set of attributes required to create a valid
  # AlternateIteming. As you add validations to AlternateIteming, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlternateItemingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all alternate_itemings as @alternate_itemings" do
      alternate_iteming = AlternateIteming.create! valid_attributes
      get :index, {}, valid_session
      assigns(:alternate_itemings).should eq([alternate_iteming])
    end
  end

  describe "GET show" do
    it "assigns the requested alternate_iteming as @alternate_iteming" do
      alternate_iteming = AlternateIteming.create! valid_attributes
      get :show, {:id => alternate_iteming.to_param}, valid_session
      assigns(:alternate_iteming).should eq(alternate_iteming)
    end
  end

  describe "GET new" do
    it "assigns a new alternate_iteming as @alternate_iteming" do
      get :new, {}, valid_session
      assigns(:alternate_iteming).should be_a_new(AlternateIteming)
    end
  end

  describe "GET edit" do
    it "assigns the requested alternate_iteming as @alternate_iteming" do
      alternate_iteming = AlternateIteming.create! valid_attributes
      get :edit, {:id => alternate_iteming.to_param}, valid_session
      assigns(:alternate_iteming).should eq(alternate_iteming)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlternateIteming" do
        expect {
          post :create, {:alternate_iteming => valid_attributes}, valid_session
        }.to change(AlternateIteming, :count).by(1)
      end

      it "assigns a newly created alternate_iteming as @alternate_iteming" do
        post :create, {:alternate_iteming => valid_attributes}, valid_session
        assigns(:alternate_iteming).should be_a(AlternateIteming)
        assigns(:alternate_iteming).should be_persisted
      end

      it "redirects to the created alternate_iteming" do
        post :create, {:alternate_iteming => valid_attributes}, valid_session
        response.should redirect_to(AlternateIteming.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alternate_iteming as @alternate_iteming" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlternateIteming.any_instance.stub(:save).and_return(false)
        post :create, {:alternate_iteming => {}}, valid_session
        assigns(:alternate_iteming).should be_a_new(AlternateIteming)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlternateIteming.any_instance.stub(:save).and_return(false)
        post :create, {:alternate_iteming => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alternate_iteming" do
        alternate_iteming = AlternateIteming.create! valid_attributes
        # Assuming there are no other alternate_itemings in the database, this
        # specifies that the AlternateIteming created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlternateIteming.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => alternate_iteming.to_param, :alternate_iteming => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested alternate_iteming as @alternate_iteming" do
        alternate_iteming = AlternateIteming.create! valid_attributes
        put :update, {:id => alternate_iteming.to_param, :alternate_iteming => valid_attributes}, valid_session
        assigns(:alternate_iteming).should eq(alternate_iteming)
      end

      it "redirects to the alternate_iteming" do
        alternate_iteming = AlternateIteming.create! valid_attributes
        put :update, {:id => alternate_iteming.to_param, :alternate_iteming => valid_attributes}, valid_session
        response.should redirect_to(alternate_iteming)
      end
    end

    describe "with invalid params" do
      it "assigns the alternate_iteming as @alternate_iteming" do
        alternate_iteming = AlternateIteming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlternateIteming.any_instance.stub(:save).and_return(false)
        put :update, {:id => alternate_iteming.to_param, :alternate_iteming => {}}, valid_session
        assigns(:alternate_iteming).should eq(alternate_iteming)
      end

      it "re-renders the 'edit' template" do
        alternate_iteming = AlternateIteming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlternateIteming.any_instance.stub(:save).and_return(false)
        put :update, {:id => alternate_iteming.to_param, :alternate_iteming => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alternate_iteming" do
      alternate_iteming = AlternateIteming.create! valid_attributes
      expect {
        delete :destroy, {:id => alternate_iteming.to_param}, valid_session
      }.to change(AlternateIteming, :count).by(-1)
    end

    it "redirects to the alternate_itemings list" do
      alternate_iteming = AlternateIteming.create! valid_attributes
      delete :destroy, {:id => alternate_iteming.to_param}, valid_session
      response.should redirect_to(alternate_itemings_url)
    end
  end

end
