require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BelievingsController do

  # This should return the minimal set of attributes required to create a valid
  # Believing. As you add validations to Believing, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BelievingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all believings as @believings" do
      believing = Believing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:believings).should eq([believing])
    end
  end

  describe "GET show" do
    it "assigns the requested believing as @believing" do
      believing = Believing.create! valid_attributes
      get :show, {:id => believing.to_param}, valid_session
      assigns(:believing).should eq(believing)
    end
  end

  describe "GET new" do
    it "assigns a new believing as @believing" do
      get :new, {}, valid_session
      assigns(:believing).should be_a_new(Believing)
    end
  end

  describe "GET edit" do
    it "assigns the requested believing as @believing" do
      believing = Believing.create! valid_attributes
      get :edit, {:id => believing.to_param}, valid_session
      assigns(:believing).should eq(believing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Believing" do
        expect {
          post :create, {:believing => valid_attributes}, valid_session
        }.to change(Believing, :count).by(1)
      end

      it "assigns a newly created believing as @believing" do
        post :create, {:believing => valid_attributes}, valid_session
        assigns(:believing).should be_a(Believing)
        assigns(:believing).should be_persisted
      end

      it "redirects to the created believing" do
        post :create, {:believing => valid_attributes}, valid_session
        response.should redirect_to(Believing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved believing as @believing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Believing.any_instance.stub(:save).and_return(false)
        post :create, {:believing => {}}, valid_session
        assigns(:believing).should be_a_new(Believing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Believing.any_instance.stub(:save).and_return(false)
        post :create, {:believing => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested believing" do
        believing = Believing.create! valid_attributes
        # Assuming there are no other believings in the database, this
        # specifies that the Believing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Believing.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => believing.to_param, :believing => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested believing as @believing" do
        believing = Believing.create! valid_attributes
        put :update, {:id => believing.to_param, :believing => valid_attributes}, valid_session
        assigns(:believing).should eq(believing)
      end

      it "redirects to the believing" do
        believing = Believing.create! valid_attributes
        put :update, {:id => believing.to_param, :believing => valid_attributes}, valid_session
        response.should redirect_to(believing)
      end
    end

    describe "with invalid params" do
      it "assigns the believing as @believing" do
        believing = Believing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Believing.any_instance.stub(:save).and_return(false)
        put :update, {:id => believing.to_param, :believing => {}}, valid_session
        assigns(:believing).should eq(believing)
      end

      it "re-renders the 'edit' template" do
        believing = Believing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Believing.any_instance.stub(:save).and_return(false)
        put :update, {:id => believing.to_param, :believing => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested believing" do
      believing = Believing.create! valid_attributes
      expect {
        delete :destroy, {:id => believing.to_param}, valid_session
      }.to change(Believing, :count).by(-1)
    end

    it "redirects to the believings list" do
      believing = Believing.create! valid_attributes
      delete :destroy, {:id => believing.to_param}, valid_session
      response.should redirect_to(believings_url)
    end
  end

end
