require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CheckinItemTagsController do

  # This should return the minimal set of attributes required to create a valid
  # CheckinItemTag. As you add validations to CheckinItemTag, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CheckinItemTagsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all checkin_item_tags as @checkin_item_tags" do
      checkin_item_tag = CheckinItemTag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:checkin_item_tags).should eq([checkin_item_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested checkin_item_tag as @checkin_item_tag" do
      checkin_item_tag = CheckinItemTag.create! valid_attributes
      get :show, {:id => checkin_item_tag.to_param}, valid_session
      assigns(:checkin_item_tag).should eq(checkin_item_tag)
    end
  end

  describe "GET new" do
    it "assigns a new checkin_item_tag as @checkin_item_tag" do
      get :new, {}, valid_session
      assigns(:checkin_item_tag).should be_a_new(CheckinItemTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested checkin_item_tag as @checkin_item_tag" do
      checkin_item_tag = CheckinItemTag.create! valid_attributes
      get :edit, {:id => checkin_item_tag.to_param}, valid_session
      assigns(:checkin_item_tag).should eq(checkin_item_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CheckinItemTag" do
        expect {
          post :create, {:checkin_item_tag => valid_attributes}, valid_session
        }.to change(CheckinItemTag, :count).by(1)
      end

      it "assigns a newly created checkin_item_tag as @checkin_item_tag" do
        post :create, {:checkin_item_tag => valid_attributes}, valid_session
        assigns(:checkin_item_tag).should be_a(CheckinItemTag)
        assigns(:checkin_item_tag).should be_persisted
      end

      it "redirects to the created checkin_item_tag" do
        post :create, {:checkin_item_tag => valid_attributes}, valid_session
        response.should redirect_to(CheckinItemTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved checkin_item_tag as @checkin_item_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheckinItemTag.any_instance.stub(:save).and_return(false)
        post :create, {:checkin_item_tag => {}}, valid_session
        assigns(:checkin_item_tag).should be_a_new(CheckinItemTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheckinItemTag.any_instance.stub(:save).and_return(false)
        post :create, {:checkin_item_tag => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested checkin_item_tag" do
        checkin_item_tag = CheckinItemTag.create! valid_attributes
        # Assuming there are no other checkin_item_tags in the database, this
        # specifies that the CheckinItemTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CheckinItemTag.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => checkin_item_tag.to_param, :checkin_item_tag => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested checkin_item_tag as @checkin_item_tag" do
        checkin_item_tag = CheckinItemTag.create! valid_attributes
        put :update, {:id => checkin_item_tag.to_param, :checkin_item_tag => valid_attributes}, valid_session
        assigns(:checkin_item_tag).should eq(checkin_item_tag)
      end

      it "redirects to the checkin_item_tag" do
        checkin_item_tag = CheckinItemTag.create! valid_attributes
        put :update, {:id => checkin_item_tag.to_param, :checkin_item_tag => valid_attributes}, valid_session
        response.should redirect_to(checkin_item_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the checkin_item_tag as @checkin_item_tag" do
        checkin_item_tag = CheckinItemTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheckinItemTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => checkin_item_tag.to_param, :checkin_item_tag => {}}, valid_session
        assigns(:checkin_item_tag).should eq(checkin_item_tag)
      end

      it "re-renders the 'edit' template" do
        checkin_item_tag = CheckinItemTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheckinItemTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => checkin_item_tag.to_param, :checkin_item_tag => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested checkin_item_tag" do
      checkin_item_tag = CheckinItemTag.create! valid_attributes
      expect {
        delete :destroy, {:id => checkin_item_tag.to_param}, valid_session
      }.to change(CheckinItemTag, :count).by(-1)
    end

    it "redirects to the checkin_item_tags list" do
      checkin_item_tag = CheckinItemTag.create! valid_attributes
      delete :destroy, {:id => checkin_item_tag.to_param}, valid_session
      response.should redirect_to(checkin_item_tags_url)
    end
  end

end
