require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FeelsController do

  # This should return the minimal set of attributes required to create a valid
  # Feel. As you add validations to Feel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FeelsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all feels as @feels" do
      feel = Feel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:feels).should eq([feel])
    end
  end

  describe "GET show" do
    it "assigns the requested feel as @feel" do
      feel = Feel.create! valid_attributes
      get :show, {:id => feel.to_param}, valid_session
      assigns(:feel).should eq(feel)
    end
  end

  describe "GET new" do
    it "assigns a new feel as @feel" do
      get :new, {}, valid_session
      assigns(:feel).should be_a_new(Feel)
    end
  end

  describe "GET edit" do
    it "assigns the requested feel as @feel" do
      feel = Feel.create! valid_attributes
      get :edit, {:id => feel.to_param}, valid_session
      assigns(:feel).should eq(feel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Feel" do
        expect {
          post :create, {:feel => valid_attributes}, valid_session
        }.to change(Feel, :count).by(1)
      end

      it "assigns a newly created feel as @feel" do
        post :create, {:feel => valid_attributes}, valid_session
        assigns(:feel).should be_a(Feel)
        assigns(:feel).should be_persisted
      end

      it "redirects to the created feel" do
        post :create, {:feel => valid_attributes}, valid_session
        response.should redirect_to(Feel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved feel as @feel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Feel.any_instance.stub(:save).and_return(false)
        post :create, {:feel => {}}, valid_session
        assigns(:feel).should be_a_new(Feel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Feel.any_instance.stub(:save).and_return(false)
        post :create, {:feel => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested feel" do
        feel = Feel.create! valid_attributes
        # Assuming there are no other feels in the database, this
        # specifies that the Feel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Feel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => feel.to_param, :feel => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested feel as @feel" do
        feel = Feel.create! valid_attributes
        put :update, {:id => feel.to_param, :feel => valid_attributes}, valid_session
        assigns(:feel).should eq(feel)
      end

      it "redirects to the feel" do
        feel = Feel.create! valid_attributes
        put :update, {:id => feel.to_param, :feel => valid_attributes}, valid_session
        response.should redirect_to(feel)
      end
    end

    describe "with invalid params" do
      it "assigns the feel as @feel" do
        feel = Feel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Feel.any_instance.stub(:save).and_return(false)
        put :update, {:id => feel.to_param, :feel => {}}, valid_session
        assigns(:feel).should eq(feel)
      end

      it "re-renders the 'edit' template" do
        feel = Feel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Feel.any_instance.stub(:save).and_return(false)
        put :update, {:id => feel.to_param, :feel => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested feel" do
      feel = Feel.create! valid_attributes
      expect {
        delete :destroy, {:id => feel.to_param}, valid_session
      }.to change(Feel, :count).by(-1)
    end

    it "redirects to the feels list" do
      feel = Feel.create! valid_attributes
      delete :destroy, {:id => feel.to_param}, valid_session
      response.should redirect_to(feels_url)
    end
  end

end
