require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NeedingsController do

  # This should return the minimal set of attributes required to create a valid
  # Needing. As you add validations to Needing, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NeedingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all needings as @needings" do
      needing = Needing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:needings).should eq([needing])
    end
  end

  describe "GET show" do
    it "assigns the requested needing as @needing" do
      needing = Needing.create! valid_attributes
      get :show, {:id => needing.to_param}, valid_session
      assigns(:needing).should eq(needing)
    end
  end

  describe "GET new" do
    it "assigns a new needing as @needing" do
      get :new, {}, valid_session
      assigns(:needing).should be_a_new(Needing)
    end
  end

  describe "GET edit" do
    it "assigns the requested needing as @needing" do
      needing = Needing.create! valid_attributes
      get :edit, {:id => needing.to_param}, valid_session
      assigns(:needing).should eq(needing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Needing" do
        expect {
          post :create, {:needing => valid_attributes}, valid_session
        }.to change(Needing, :count).by(1)
      end

      it "assigns a newly created needing as @needing" do
        post :create, {:needing => valid_attributes}, valid_session
        assigns(:needing).should be_a(Needing)
        assigns(:needing).should be_persisted
      end

      it "redirects to the created needing" do
        post :create, {:needing => valid_attributes}, valid_session
        response.should redirect_to(Needing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved needing as @needing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Needing.any_instance.stub(:save).and_return(false)
        post :create, {:needing => {}}, valid_session
        assigns(:needing).should be_a_new(Needing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Needing.any_instance.stub(:save).and_return(false)
        post :create, {:needing => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested needing" do
        needing = Needing.create! valid_attributes
        # Assuming there are no other needings in the database, this
        # specifies that the Needing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Needing.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => needing.to_param, :needing => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested needing as @needing" do
        needing = Needing.create! valid_attributes
        put :update, {:id => needing.to_param, :needing => valid_attributes}, valid_session
        assigns(:needing).should eq(needing)
      end

      it "redirects to the needing" do
        needing = Needing.create! valid_attributes
        put :update, {:id => needing.to_param, :needing => valid_attributes}, valid_session
        response.should redirect_to(needing)
      end
    end

    describe "with invalid params" do
      it "assigns the needing as @needing" do
        needing = Needing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Needing.any_instance.stub(:save).and_return(false)
        put :update, {:id => needing.to_param, :needing => {}}, valid_session
        assigns(:needing).should eq(needing)
      end

      it "re-renders the 'edit' template" do
        needing = Needing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Needing.any_instance.stub(:save).and_return(false)
        put :update, {:id => needing.to_param, :needing => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested needing" do
      needing = Needing.create! valid_attributes
      expect {
        delete :destroy, {:id => needing.to_param}, valid_session
      }.to change(Needing, :count).by(-1)
    end

    it "redirects to the needings list" do
      needing = Needing.create! valid_attributes
      delete :destroy, {:id => needing.to_param}, valid_session
      response.should redirect_to(needings_url)
    end
  end

end
