require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NeedFulfilledStatingsController do

  # This should return the minimal set of attributes required to create a valid
  # NeedFulfilledStating. As you add validations to NeedFulfilledStating, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NeedFulfilledStatingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all need_fulfilled_statings as @need_fulfilled_statings" do
      need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
      get :index, {}, valid_session
      assigns(:need_fulfilled_statings).should eq([need_fulfilled_stating])
    end
  end

  describe "GET show" do
    it "assigns the requested need_fulfilled_stating as @need_fulfilled_stating" do
      need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
      get :show, {:id => need_fulfilled_stating.to_param}, valid_session
      assigns(:need_fulfilled_stating).should eq(need_fulfilled_stating)
    end
  end

  describe "GET new" do
    it "assigns a new need_fulfilled_stating as @need_fulfilled_stating" do
      get :new, {}, valid_session
      assigns(:need_fulfilled_stating).should be_a_new(NeedFulfilledStating)
    end
  end

  describe "GET edit" do
    it "assigns the requested need_fulfilled_stating as @need_fulfilled_stating" do
      need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
      get :edit, {:id => need_fulfilled_stating.to_param}, valid_session
      assigns(:need_fulfilled_stating).should eq(need_fulfilled_stating)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NeedFulfilledStating" do
        expect {
          post :create, {:need_fulfilled_stating => valid_attributes}, valid_session
        }.to change(NeedFulfilledStating, :count).by(1)
      end

      it "assigns a newly created need_fulfilled_stating as @need_fulfilled_stating" do
        post :create, {:need_fulfilled_stating => valid_attributes}, valid_session
        assigns(:need_fulfilled_stating).should be_a(NeedFulfilledStating)
        assigns(:need_fulfilled_stating).should be_persisted
      end

      it "redirects to the created need_fulfilled_stating" do
        post :create, {:need_fulfilled_stating => valid_attributes}, valid_session
        response.should redirect_to(NeedFulfilledStating.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved need_fulfilled_stating as @need_fulfilled_stating" do
        # Trigger the behavior that occurs when invalid params are submitted
        NeedFulfilledStating.any_instance.stub(:save).and_return(false)
        post :create, {:need_fulfilled_stating => {}}, valid_session
        assigns(:need_fulfilled_stating).should be_a_new(NeedFulfilledStating)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NeedFulfilledStating.any_instance.stub(:save).and_return(false)
        post :create, {:need_fulfilled_stating => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested need_fulfilled_stating" do
        need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
        # Assuming there are no other need_fulfilled_statings in the database, this
        # specifies that the NeedFulfilledStating created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NeedFulfilledStating.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => need_fulfilled_stating.to_param, :need_fulfilled_stating => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested need_fulfilled_stating as @need_fulfilled_stating" do
        need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
        put :update, {:id => need_fulfilled_stating.to_param, :need_fulfilled_stating => valid_attributes}, valid_session
        assigns(:need_fulfilled_stating).should eq(need_fulfilled_stating)
      end

      it "redirects to the need_fulfilled_stating" do
        need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
        put :update, {:id => need_fulfilled_stating.to_param, :need_fulfilled_stating => valid_attributes}, valid_session
        response.should redirect_to(need_fulfilled_stating)
      end
    end

    describe "with invalid params" do
      it "assigns the need_fulfilled_stating as @need_fulfilled_stating" do
        need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NeedFulfilledStating.any_instance.stub(:save).and_return(false)
        put :update, {:id => need_fulfilled_stating.to_param, :need_fulfilled_stating => {}}, valid_session
        assigns(:need_fulfilled_stating).should eq(need_fulfilled_stating)
      end

      it "re-renders the 'edit' template" do
        need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NeedFulfilledStating.any_instance.stub(:save).and_return(false)
        put :update, {:id => need_fulfilled_stating.to_param, :need_fulfilled_stating => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested need_fulfilled_stating" do
      need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
      expect {
        delete :destroy, {:id => need_fulfilled_stating.to_param}, valid_session
      }.to change(NeedFulfilledStating, :count).by(-1)
    end

    it "redirects to the need_fulfilled_statings list" do
      need_fulfilled_stating = NeedFulfilledStating.create! valid_attributes
      delete :destroy, {:id => need_fulfilled_stating.to_param}, valid_session
      response.should redirect_to(need_fulfilled_statings_url)
    end
  end

end
