require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ThoughtAlternateFramingsController do

  # This should return the minimal set of attributes required to create a valid
  # ThoughtAlternateFraming. As you add validations to ThoughtAlternateFraming, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThoughtAlternateFramingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all thought_alternate_framings as @thought_alternate_framings" do
      thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
      get :index, {}, valid_session
      assigns(:thought_alternate_framings).should eq([thought_alternate_framing])
    end
  end

  describe "GET show" do
    it "assigns the requested thought_alternate_framing as @thought_alternate_framing" do
      thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
      get :show, {:id => thought_alternate_framing.to_param}, valid_session
      assigns(:thought_alternate_framing).should eq(thought_alternate_framing)
    end
  end

  describe "GET new" do
    it "assigns a new thought_alternate_framing as @thought_alternate_framing" do
      get :new, {}, valid_session
      assigns(:thought_alternate_framing).should be_a_new(ThoughtAlternateFraming)
    end
  end

  describe "GET edit" do
    it "assigns the requested thought_alternate_framing as @thought_alternate_framing" do
      thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
      get :edit, {:id => thought_alternate_framing.to_param}, valid_session
      assigns(:thought_alternate_framing).should eq(thought_alternate_framing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ThoughtAlternateFraming" do
        expect {
          post :create, {:thought_alternate_framing => valid_attributes}, valid_session
        }.to change(ThoughtAlternateFraming, :count).by(1)
      end

      it "assigns a newly created thought_alternate_framing as @thought_alternate_framing" do
        post :create, {:thought_alternate_framing => valid_attributes}, valid_session
        assigns(:thought_alternate_framing).should be_a(ThoughtAlternateFraming)
        assigns(:thought_alternate_framing).should be_persisted
      end

      it "redirects to the created thought_alternate_framing" do
        post :create, {:thought_alternate_framing => valid_attributes}, valid_session
        response.should redirect_to(ThoughtAlternateFraming.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thought_alternate_framing as @thought_alternate_framing" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThoughtAlternateFraming.any_instance.stub(:save).and_return(false)
        post :create, {:thought_alternate_framing => {}}, valid_session
        assigns(:thought_alternate_framing).should be_a_new(ThoughtAlternateFraming)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ThoughtAlternateFraming.any_instance.stub(:save).and_return(false)
        post :create, {:thought_alternate_framing => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested thought_alternate_framing" do
        thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
        # Assuming there are no other thought_alternate_framings in the database, this
        # specifies that the ThoughtAlternateFraming created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ThoughtAlternateFraming.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => thought_alternate_framing.to_param, :thought_alternate_framing => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested thought_alternate_framing as @thought_alternate_framing" do
        thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
        put :update, {:id => thought_alternate_framing.to_param, :thought_alternate_framing => valid_attributes}, valid_session
        assigns(:thought_alternate_framing).should eq(thought_alternate_framing)
      end

      it "redirects to the thought_alternate_framing" do
        thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
        put :update, {:id => thought_alternate_framing.to_param, :thought_alternate_framing => valid_attributes}, valid_session
        response.should redirect_to(thought_alternate_framing)
      end
    end

    describe "with invalid params" do
      it "assigns the thought_alternate_framing as @thought_alternate_framing" do
        thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThoughtAlternateFraming.any_instance.stub(:save).and_return(false)
        put :update, {:id => thought_alternate_framing.to_param, :thought_alternate_framing => {}}, valid_session
        assigns(:thought_alternate_framing).should eq(thought_alternate_framing)
      end

      it "re-renders the 'edit' template" do
        thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ThoughtAlternateFraming.any_instance.stub(:save).and_return(false)
        put :update, {:id => thought_alternate_framing.to_param, :thought_alternate_framing => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thought_alternate_framing" do
      thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
      expect {
        delete :destroy, {:id => thought_alternate_framing.to_param}, valid_session
      }.to change(ThoughtAlternateFraming, :count).by(-1)
    end

    it "redirects to the thought_alternate_framings list" do
      thought_alternate_framing = ThoughtAlternateFraming.create! valid_attributes
      delete :destroy, {:id => thought_alternate_framing.to_param}, valid_session
      response.should redirect_to(thought_alternate_framings_url)
    end
  end

end
