require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WithoutItemsController do

  # This should return the minimal set of attributes required to create a valid
  # WithoutItem. As you add validations to WithoutItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WithoutItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all without_items as @without_items" do
      without_item = WithoutItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:without_items).should eq([without_item])
    end
  end

  describe "GET show" do
    it "assigns the requested without_item as @without_item" do
      without_item = WithoutItem.create! valid_attributes
      get :show, {:id => without_item.to_param}, valid_session
      assigns(:without_item).should eq(without_item)
    end
  end

  describe "GET new" do
    it "assigns a new without_item as @without_item" do
      get :new, {}, valid_session
      assigns(:without_item).should be_a_new(WithoutItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested without_item as @without_item" do
      without_item = WithoutItem.create! valid_attributes
      get :edit, {:id => without_item.to_param}, valid_session
      assigns(:without_item).should eq(without_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WithoutItem" do
        expect {
          post :create, {:without_item => valid_attributes}, valid_session
        }.to change(WithoutItem, :count).by(1)
      end

      it "assigns a newly created without_item as @without_item" do
        post :create, {:without_item => valid_attributes}, valid_session
        assigns(:without_item).should be_a(WithoutItem)
        assigns(:without_item).should be_persisted
      end

      it "redirects to the created without_item" do
        post :create, {:without_item => valid_attributes}, valid_session
        response.should redirect_to(WithoutItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved without_item as @without_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        WithoutItem.any_instance.stub(:save).and_return(false)
        post :create, {:without_item => {}}, valid_session
        assigns(:without_item).should be_a_new(WithoutItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WithoutItem.any_instance.stub(:save).and_return(false)
        post :create, {:without_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested without_item" do
        without_item = WithoutItem.create! valid_attributes
        # Assuming there are no other without_items in the database, this
        # specifies that the WithoutItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WithoutItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => without_item.to_param, :without_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested without_item as @without_item" do
        without_item = WithoutItem.create! valid_attributes
        put :update, {:id => without_item.to_param, :without_item => valid_attributes}, valid_session
        assigns(:without_item).should eq(without_item)
      end

      it "redirects to the without_item" do
        without_item = WithoutItem.create! valid_attributes
        put :update, {:id => without_item.to_param, :without_item => valid_attributes}, valid_session
        response.should redirect_to(without_item)
      end
    end

    describe "with invalid params" do
      it "assigns the without_item as @without_item" do
        without_item = WithoutItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WithoutItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => without_item.to_param, :without_item => {}}, valid_session
        assigns(:without_item).should eq(without_item)
      end

      it "re-renders the 'edit' template" do
        without_item = WithoutItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WithoutItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => without_item.to_param, :without_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested without_item" do
      without_item = WithoutItem.create! valid_attributes
      expect {
        delete :destroy, {:id => without_item.to_param}, valid_session
      }.to change(WithoutItem, :count).by(-1)
    end

    it "redirects to the without_items list" do
      without_item = WithoutItem.create! valid_attributes
      delete :destroy, {:id => without_item.to_param}, valid_session
      response.should redirect_to(without_items_url)
    end
  end

end
