# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
    Role.create(name: "admin")
    Role.create(name: "user")

    # User age is between 18 to 40
    User.create(name: "Chaitanya Gaikwad",role_id: 1,email: 'chaitany51@gmail.com', gender: 'M', age: 21)
    User.create(name: "Sushant Mane",role_id: 2,email: 'sushantmane7@gmail.com', gender: 'M', age: 21)
    User.create(name: "Rajat Rokade",role_id: 2,email: 'Rajatrokade@gmail.com', gender: 'M', age: 22)
    User.create(name: "Kiran Bedi",role_id: 2,email: 'Kiranbedi@gmail.com', gender: 'F', age: 22)
    User.create(name: "Kiran Bedi2",role_id: 2,email: 'Kiranbedi2@gmail.com', gender: 'F', age: 20)

    Survey.create(name: 'coderetreat', type_of_survey:'general',conducted: '2015-2-1',no_of_people: 2,question_count: 5)
    Survey.create(name: 'coderetreat2', type_of_survey: 'typical', conducted: '2015-1-1', no_of_people: 3,question_count: 5)
    Survey.create(name: 'no questions', type_of_survey: 'blank', conducted:'2014-04-29', no_of_people: 2,question_count: 0)
    Question.create(question: 'what is review?', survey_id: 1)
    Question.create(question: 'what is review2?', survey_id: 1)
    Question.create(question: 'what is review3?', survey_id: 1)
    Question.create(question: 'what is review4?', survey_id: 1)
    Question.create(question: 'what is review5?', survey_id: 1)
    Question.create(question: 'what is review6?', survey_id: 2)
    Question.create(question: 'what is review7?', survey_id: 2)
    Question.create(question: 'what is review8?', survey_id: 2)
    Question.create(question: 'what is review9?', survey_id: 2)
    Question.create(question: 'what is review10?', survey_id: 2)

    Option.create(option: 'good',question_id: 1)
    Option.create(option: 'better',question_id: 1)
    Option.create(option: 'best',question_id: 1)
    Option.create(option: 'worst',question_id: 1)
    Option.create(option: 'good',question_id: 2)
    Option.create(option: 'better',question_id: 2)
    Option.create(option: 'best',question_id: 2)
    Option.create(option: 'worst',question_id: 2)
    Option.create(option: 'good',question_id: 3)
    Option.create(option: 'better',question_id: 3)
    Option.create(option: 'best',question_id: 3)
    Option.create(option: 'worst',question_id: 3)
    Option.create(option: 'good',question_id: 4)
    Option.create(option: 'better',question_id: 4)
    Option.create(option: 'best',question_id: 4)
    Option.create(option: 'worst',question_id: 4)
    Option.create(option: 'good',question_id: 5)
    Option.create(option: 'better',question_id: 5)
    Option.create(option: 'best',question_id: 5)
    Option.create(option: 'worst',question_id: 5)
    Option.create(option: 'good',question_id: 6)
    Option.create(option: 'better',question_id: 6)
    Option.create(option: 'best',question_id: 6)
    Option.create(option: 'worst',question_id: 6)
    Option.create(option: 'good',question_id: 7)
    Option.create(option: 'better',question_id: 7)
    Option.create(option: 'best',question_id: 7)
    Option.create(option: 'worst',question_id: 7)
    Option.create(option: 'good',question_id: 8)
    Option.create(option: 'better',question_id: 8)
    Option.create(option: 'best',question_id: 8)
    Option.create(option: 'worst',question_id: 8)
    Option.create(option: 'good',question_id: 9)
    Option.create(option: 'better',question_id: 9)
    Option.create(option: 'best',question_id: 9)
    Option.create(option: 'worst',question_id: 9)
    Option.create(option: 'good',question_id: 10)
    Option.create(option: 'better',question_id: 10)
    Option.create(option: 'best',question_id: 10)
    Option.create(option: 'worst',question_id: 10)

    # Responses 25 responses
     
    Response.create(option_id: 1,user_id: 1)
    Response.create(option_id: 6,user_id: 1)
    Response.create(option_id: 10,user_id: 1)
    Response.create(option_id: 13,user_id: 1)
    Response.create(option_id: 17,user_id: 1)
    Response.create(option_id: 2,user_id: 2)
    Response.create(option_id: 7,user_id: 2)
    Response.create(option_id: 10,user_id: 2)
    Response.create(option_id: 14,user_id: 2)
    Response.create(option_id: 18,user_id: 2)
    Response.create(option_id: 23,user_id: 3)
    Response.create(option_id: 26,user_id: 3)
    Response.create(option_id: 30,user_id: 3)
    Response.create(option_id: 33,user_id: 3)
    Response.create(option_id: 37,user_id: 3)
    Response.create(option_id: 22,user_id: 4)
    Response.create(option_id: 27,user_id: 4)
    Response.create(option_id: 30,user_id: 4)
    Response.create(option_id: 34,user_id: 4)
    Response.create(option_id: 38,user_id: 4)
    Response.create(option_id: 21,user_id: 5)
    Response.create(option_id: 27,user_id: 5)
    Response.create(option_id: 30,user_id: 5)
    Response.create(option_id: 33,user_id: 5)
    Response.create(option_id: 37,user_id: 5)

